config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users
  resources :blogs do
    resources :comments, only: [:create]
  end

  get 'search', to: 'blogs#search', as: :search
  get 'tags/:tag', to: 'blogs#show_blog_tagged', as: :tag
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    after_initialize :set_defaults, unless: :persisted?
    belongs_to :user
    has_many :comments

    acts_as_taggable

    def set_defaults
        self.nb_view  ||= 0
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
    has_many :blogs
    has_many :comments

    has_secure_password

    validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
   private
   def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end

   helper_method :current_user

   def authorize
    if current_user.nil?
        flash[:error] = "Not authorized"
        redirect_to login_url
    end
   end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authorize, only: [:create, :edit, :update, :destroy]

  def index
    @blogs = Blog.all.order("created_at DESC").page(params[:page]).per_page(5)
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
    @comment = Comment.new

    @blog.record_timestamps = false
    @blog.update_attributes(:nb_view => @blog.nb_view.to_i + 1)
    @blog.record_timestamps = true
  end

  def create
    @blog = current_user.blogs.create!(blog_params)

    flash[:success] = "Blog successfully created!"
    redirect_to blogs_url
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(blog_params)

    redirect_to blog_path(params[:id])
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.comments.each do |comment|
      comment.destroy
    end
    @blog.destroy

    flash[:success] = "Blog successfully deleted!"
    redirect_to blogs_url
  end

  def search
    keywords = params.require(:keywords)
    @blogs = Blog.where("lower(title) like ?", "%#{keywords.downcase}%").page(params[:page]).per_page(5)
  end

  def show_blog_tagged
    @tag = params.require(:tag)
    @blogs = Blog.tagged_with(@tag).page(params[:page]).per_page(5)
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :tag_list)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_blog
    before_filter :authorize, only: [:create]

    def create
        @comment = @blog.comments.create!(comment_params)
        
        redirect_to blog_path(@blog.id)
    end


    def find_blog
        @blog = Blog.find(params[:blog_id])
    end

    private 
    def comment_params
        params.require(:comment).permit(:content).merge!(user: current_user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in successfully!"
      redirect_to blogs_url
    else
      flash[:error] = "Email or password is invalid."
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out successfully!"
    redirect_to blogs_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)

        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Account successfully created!"
            redirect_to blogs_url
        else
            render "new"
        end
    end

    private
    def user_params
        params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
        renderer = Redcarpet::Render::HTML.new(filter_html: true, hard_wrap: true)
        markdown = Redcarpet::Markdown.new(renderer, auto_link: true, no_intra_emphasis: true)
        markdown.render(text).html_safe
    end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog/home.html.erb
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    Page Heading
                    <small>Secondary Text</small>
                </h1>

                 <!-- Blog form -->
                <div class="well" style="min-height:250px">
                    <h4>Create new entry:</h4>
                    <form role="form">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Enter title">
                            </br>
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary pull-right">Submit</button>
                    </form>
                </div>

                <hr>


                <!-- First Blog Post -->
                <h2>
                    <a href="#">Blog Post Title</a>
                </h2>
                <p class="lead">
                    by <a href="index.php">Start Bootstrap</a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM</p>
                <hr>
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                <hr>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, veritatis, tempora, necessitatibus inventore nisi quam quia repellat ut tempore laborum possimus eum dicta id animi corrupti debitis ipsum officiis rerum.</p>
                <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

                <hr>

                <!-- Second Blog Post -->
                <h2>
                    <a href="#">Blog Post Title</a>
                </h2>
                <p class="lead">
                    by <a href="index.php">Start Bootstrap</a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:45 PM</p>
                <hr>
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                <hr>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam, quasi, fugiat, asperiores harum voluptatum tenetur a possimus nesciunt quod accusamus saepe tempora ipsam distinctio minima dolorum perferendis labore impedit voluptates!</p>
                <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

                <hr>

                <!-- Third Blog Post -->
                <h2>
                    <a href="#">Blog Post Title</a>
                </h2>
                <p class="lead">
                    by <a href="index.php">Start Bootstrap</a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:45 PM</p>
                <hr>
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                <hr>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, voluptates, voluptas dolore ipsam cumque quam veniam accusantium laudantium adipisci architecto itaque dicta aperiam maiores provident id incidunt autem. Magni, ratione.</p>
                <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

                <hr>

                <!-- Pager -->
                <ul class="pager">
                    <li class="previous">
                        <a href="#">&larr; Older</a>
                    </li>
                    <li class="next">
                        <a href="#">Newer &rarr;</a>
                    </li>
                </ul>

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

app/views/blogs/_pager.html.erb
<!-- Pager -->
                <ul class="pager">
                    <% if @blogs.next_page %>
                        <li class="previous">
                            <%= link_to "&larr; Older".html_safe, params.merge(:page => @blogs.next_page).permit! %>
                        </li>
                    <% end %>

                    <% if @blogs.previous_page %>
                        <li class="next">
                            <%= link_to "Newer &rarr;".html_safe, params.merge(:page => @blogs.previous_page).permit! %>
                        </li>
                    <% end %>
                </ul>

app/views/blogs/_sidebar.html.erb
<!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4" style="margin-top: 109px">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Search</h4>
                    <%= form_tag(search_url, method: "get") do %>
                        <div class="input-group">
                            <%= text_field_tag "keywords", nil, class: "form-control", placeholder: "Search blog by title" %>
                            <span class="input-group-btn">
                                <%= button_tag nil, class: "btn btn-default" do %>
                                    <span class="glyphicon glyphicon-search"></span>
                                <% end %>
                            </span>
                        </div>
                    <% end %>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Tags</h4>
                    <div class="row">
                        <div class="col-lg-12">
                            <% if Blog.tag_counts.empty? %>
                                No tag
                            <% end %>
                            <div id="tag-cloud">
                                <% tag_cloud Blog.tag_counts, %w[s m l] do |tag, css_class| %>
                                    <%= link_to  tag.name, tag_path(tag.name), class: css_class %>
                                <% end %>
                            </div>
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                    <!-- /.row -->
                </div>

            </div>

app/views/blogs/index.html.erb
    <% content_for :title, "Home - IsaBéry" %>
    
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    Timeline
                </h1>

                <% if flash[:success].present? %>
                    <div class="alert alert-success" role="alert"><%= flash[:success] %></div>
                <% end %>

                <% if current_user %>
                    <!-- Blog form -->
                    <div class="well" style="min-height:430px">
                        <h4>Create new entry:</h4>
                        <%= form_for @blog, url: {action: "create"}, html: {role: "form"} do |f| %>
                            <div class="form-group">
                                <%= f.label :title %>
                                <%= f.text_field :title, class: "form-control", placeholder: "Enter title", required: true %>
                                </br>
                                <%= f.label :content %>
                                <%= f.text_area :content, rows: 5, class: "form-control", required: true %>
                                </br>
                                <%= f.label :tag_list, "Tags (separated by commas)" %>
                                <%= f.text_field :tag_list, class: "form-control", placeholder: "Enter tags" %>
                            </div>
                            <%= f.submit "Submit", class: "btn btn-primary pull-right" %>
                        <% end %>
                    </div>
                <% else %>
                    <div class="well">
                        <h2 style="text-align: center"><%= link_to 'Log in', login_path %> or <%= link_to 'Sign up', signup_path %> to create new Entry?</h2>
                    </div>
                <% end %>

                <hr>

                <% @blogs.each do |blog| %>
                <div>
                    <h2>
                        <%= link_to blog.title, blog %>
                    </h2>
                    <p class="lead">
                        by <%= blog.user.firstname %> <%= blog.user.lastname %>
                    </p>
                    <% if blog.created_at == blog.updated_at %>
                    <p><span class="glyphicon glyphicon-time"></span> Posted <%= time_ago_in_words(blog.created_at) %></p>
                    <% else %>
                    <p><span class="glyphicon glyphicon-time"></span> Edited <%= time_ago_in_words(blog.updated_at) %></p>
                    <% end %>
                    <hr>
                    <p><%= blog.content.lines.first %> </p>
                    <hr>
                    <% if blog.tag_list.empty? %>
                        <p><small> No tag </small></p>
                    <% else %>
                        <p><small>Tags: <%= blog.tag_list.map { |t| link_to t, tag_path(t) }.join(', ').html_safe %></small></p>
                    <% end %>

                    <%= link_to blog, class: "btn btn-primary" do %>
                        Read more
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    <% end %>

                    <hr>
                </div>
                <% end %>

                <%= render 'blogs/pager' %>

            </div>

            <%= render 'blogs/sidebar' %>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

app/views/blogs/search.html.erb
    <% content_for :title, "Search result - IsaBéry" %>
    
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    Search Results
                </h1>

                <% if @blogs.empty? %>
                    <h1 style="text-align: center"> Blog not found! </h1>
                <% end %>

                <% @blogs.each do |blog| %>
                <div>
                    <h2>
                        <%= link_to blog.title, blog %>
                    </h2>
                    <p class="lead">
                        by <%= blog.user.firstname %> <%= blog.user.lastname %>
                    </p>
                    <% if blog.created_at == blog.updated_at %>
                    <p><span class="glyphicon glyphicon-time"></span> Posted <%= time_ago_in_words(blog.created_at) %></p>
                    <% else %>
                    <p><span class="glyphicon glyphicon-time"></span> Edited <%= time_ago_in_words(blog.updated_at) %></p>
                    <% end %>
                    <hr>
                    <p><%= blog.content.lines.first %> </p>

                    <p><small>Tags: <%= blog.tag_list.map { |t| link_to t, tag_path(t) }.join(', ').html_safe %></small></p>

                    <%= link_to blog, class: "btn btn-primary" do %>
                        Read more
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    <% end %>

                    <hr>
                </div>
                <% end %>

                <%= render 'blogs/pager' %>

            </div>

            <%= render 'blogs/sidebar' %>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

app/views/blogs/show.html.erb
<% content_for :title, @blog.title + " - IsaBéry" %>

<script>
   $('.dropdown-toggle').dropdown()
</script>

<!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Blog Post -->

                <!-- Edit & Delete-->
                <% if @blog.user == current_user %>
                    <div class="btn-group pull-right">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-cog">
                        </button>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Edit", edit_blog_path(@blog.id), class: "dropdown-item" %></li>
                            <li><%= link_to 'Delete',  { action: :destroy, id: @blog.id }, method: :delete, data: { confirm: 'Do you really want to delete this blog?' } %></li>
                        </ul>
                    </div>
                <% end %>

                <!-- Title -->
                <h1><%= @blog.title %></h1>

                <!-- Author -->
                <p class="lead">
                    by <%= @blog.user.firstname %> <%= @blog.user.lastname %>
                </p>

                <hr>

                <!-- View -->
                <% if @blog.nb_view > 1 %>
                    <small class="pull-right"><%= @blog.nb_view %> views</small>
                <% elsif @blog.nb_view == 1 %>
                    <small class="pull-right">1 view</small>
                <% else %>
                    <small class="pull-right">No view</small>
                <% end %>               

                <!-- Date/Time -->
                <% if @blog.created_at == @blog.updated_at %>
                    <p><span class="glyphicon glyphicon-time"></span> Posted <%= time_ago_in_words(@blog.created_at) %></p>
                <% else %>
                    <p><span class="glyphicon glyphicon-time"></span> Edited <%= time_ago_in_words(@blog.updated_at) %></p>
                <% end %>


                <hr>

                <!-- Post Content -->
                <p class="lead"><%= markdown(@blog.content) %></p>
                
                <hr>

                <% if @blog.tag_list.empty? %>
                    <small> No tag </small>
                <% else %>
                    <small>Tags: <%= @blog.tag_list.map { |t| link_to t, tag_path(t) }.join(', ').html_safe %></small>
                <% end %>

                <hr>

                <!-- Blog Comments -->

                <% if current_user %>
                    <!-- Comments Form -->
                    <div class="well" style="height: 200px">
                        <h4>Leave a Comment:</h4>
                        <%= form_for [@blog, @comment], html: {role: "form"} do |f| %>
                            <div class="form-group">
                                <%= f.text_area :content, rows: 3, class: "form-control", required: true %>
                            </div>
                            <%= f.submit "Submit", class: "btn btn-primary pull-right" %>
                        <% end %>
                    </div>
                <% else %>
                    <div class="well">
                        <h2 style="text-align: center"><%= link_to 'Log in', login_path %> or <%= link_to 'Sign up', signup_path %> to leave a Comment?</h2>
                    </div>
                <% end %>

                <% if @blog.comments.count == 1 %>
                    <h2><%= @blog.comments.count %> comment</h2>
                <% elsif @blog.comments.count > 1 %>
                    <h2><%= @blog.comments.count %> comments</h2>
                <% else %>
                    <h2>No comment</h2>
                <% end %>    

                <hr>
                 <% @blog.comments.order("created_at DESC").each do |comment| %>

                    <!-- Comment -->
                    <div class="media" style="margin-bottom: 20px">
                        <a class="pull-left" href="#">
                            <img class="media-object" src="http://placehold.it/64x64" alt="">
                        </a>
                        <div class="media-body">
                            <h4 class="media-heading"> <%= comment.user.firstname %> <%= comment.user.lastname %>
                                <small><%= time_ago_in_words(comment.created_at) %></small>
                            </h4>
                            <%= markdown(comment.content) %>
                        </div>
                    </div>
                    <hr>
                <% end %>
            </div>

            <%= render 'blogs/sidebar' %>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

app/views/blogs/show_blog_tagged.html.erb
    <% content_for :title, 'Tag: "' + @tag + '" - IsaBéry' %>
    
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    Blogs with Tag "<%= @tag %>"
                </h1>

                <% if @blogs.empty? %>
                    <h1 style="text-align: center"> Blog not found! </h1>
                <% end %>

                <% @blogs.each do |blog| %>
                <div>
                    <h2>
                        <%= link_to blog.title, blog %>
                    </h2>
                    <p class="lead">
                        by <%= blog.user.firstname %> <%= blog.user.lastname %>
                    </p>
                    <% if blog.created_at == blog.updated_at %>
                    <p><span class="glyphicon glyphicon-time"></span> Posted <%= time_ago_in_words(blog.created_at) %></p>
                    <% else %>
                    <p><span class="glyphicon glyphicon-time"></span> Edited <%= time_ago_in_words(blog.updated_at) %></p>
                    <% end %>
                    <hr>
                    <p><%= blog.content.lines.first %> </p>

                    <p><small>Tags: <%= blog.tag_list.map { |t| link_to t, tag_path(t) }.join(', ').html_safe %></small></p>

                    <%= link_to blog, class: "btn btn-primary" do %>
                        Read more
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    <% end %>

                    <hr>
                </div>
                <% end %>

                <%= render 'blogs/pager' %>

            </div>

            <%= render 'blogs/sidebar' %>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "IsaBéry", blogs_url, class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <% if current_user %>
                        <li><a style="cursor: default"><span class="glyphicon glyphicon-user"> <%= current_user.firstname %> <%= current_user.lastname %></a></li>
                        <li><%= link_to '<span class="glyphicon glyphicon-log-out"></span> Log Out'.html_safe, logout_path %></li>
                    <% else %>
                        <li><%= link_to '<span class="glyphicon glyphicon-user"></span> Sign Up'.html_safe, signup_path %></li>
                        <li><%= link_to '<span class="glyphicon glyphicon-log-in"></span> Log In'.html_safe, login_path %></li>
                    <% end %>
				</ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <%= yield %>

    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            <p class="text-muted">Copyright &copy; IsaBéry</p>
        </div>
    </footer>
  </body>
</html>

app/views/users/new.html.erb
<% content_for :title, "Sign up - IsaBéry" %>

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="container">
				<div class="row">
					<div class="col-sm-6 col-md-4 col-md-offset-4">

                        <% if @user.errors.any? %>
                            <div class="alert alert-danger" role="alert">
								<h2> Form is invalid </h2>
								<ul>
                                    <% @user.errors.full_messages.each do |m| %>
									    <li><%= m %></li>
                                    <% end %>
								</ul>
							</div>
                        <% end %>

						<h1 class="text-center login-title">Sign up to IsaBéry</h1>
						<div class="account-wall">
                            <%= form_for @user, html: {class: "form-signin"} do |f| %>
                                <div class="form-group">
                                    <%= f.label :email, class: "control-label" %>
                                    <%= f.email_field :email, class: "form-control", placeholder: "Enter email address", required: true %>
                                </div>

                                <div class="form-group">
                                    <%= f.label :firstname, class: "control-label" %>
                                    <%= f.text_field :firstname, class: "form-control", placeholder: "Enter first name", required: true %>
                                </div>

                                <div class="form-group">
                                    <%= f.label :lastname, class: "control-label" %>
                                    <%= f.text_field :lastname, class: "form-control", placeholder: "Enter last name", required: true %>
                                </div>

                                <div class="form-group">
                                    <%= f.label :password, class: "control-label" %>
                                    <%= f.password_field :password, class: "form-control", placeholder: "Enter password", required: true %>
                                </div>

                                <div class="form-group">
                                    <%= f.label :password_confirmation, class: "control-label" %>
                                    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password confirmation", required: true %>
                                </div>

                                <%= f.submit "Sign up", class: "btn btn-lg btn-primary btn-block" %>
                            <% end %>
						</div>
						<span class="text-center new-account">Already have an account?</span>
                        <%= link_to "Log in", login_path, class: "text-center new-account" %>
					</div>
				</div>
			</div>
        </div>
    </div>
</div>